/* ==========================================================
   AssemblyBench — Built-in part library
   These are real, well-known sequences from public sources, included
   as teaching examples. Trim to a sensible educational length.
   ========================================================== */

const PART_TYPE_META = {
  promoter:    { label: 'Promoter',    color: '#3b82f6', tip: 'Tells the cell where to start transcribing. Comes BEFORE the gene.' },
  rbs:         { label: 'RBS',         color: '#10b981', tip: 'Ribosome binding site. Sits between the promoter and the start codon of the CDS.' },
  cds:         { label: 'CDS',         color: '#f59e0b', tip: 'Coding sequence. The actual gene that gets translated into protein.' },
  terminator:  { label: 'Terminator',  color: '#ef4444', tip: 'Stops transcription. Goes right after the CDS.' },
  origin:      { label: 'Origin',      color: '#8b5cf6', tip: 'Origin of replication — lets the plasmid copy itself in the host cell.' },
  resistance:  { label: 'Marker',      color: '#06b6d4', tip: 'Antibiotic resistance gene. Selects for cells that took up the plasmid.' },
  other:       { label: 'Other',       color: '#94a3b8', tip: 'A custom or unclassified DNA fragment (e.g. spacer, tag, linker).' },
};

/* The library is intentionally small — enough to assemble a working
   demo plasmid without overwhelming a beginner. */
const PART_LIBRARY = [
  // ---- Promoters ----
  {
    id: 'p_T7',
    type: 'promoter',
    name: 'T7 promoter',
    summary: 'Strong bacteriophage T7 promoter. Requires T7 RNA polymerase in the host.',
    sequence: 'TAATACGACTCACTATAGGG',
  },
  {
    id: 'p_lac',
    type: 'promoter',
    name: 'lac promoter',
    summary: 'Classic IPTG-inducible promoter from E. coli.',
    sequence: 'TTTACACTTTATGCTTCCGGCTCGTATGTTGTGTGGAATTGTGAGCGGATAACAATTTCACACAGG',
  },
  {
    id: 'p_J23100',
    type: 'promoter',
    name: 'J23100 (constitutive)',
    summary: 'Strong constitutive promoter from the Anderson family (iGEM Registry).',
    sequence: 'TTGACGGCTAGCTCAGTCCTAGGTACAGTGCTAGC',
  },
  {
    id: 'p_pTEF1',
    type: 'promoter',
    name: 'pTEF1 (yeast)',
    summary: 'Strong constitutive promoter from S. cerevisiae TEF1.',
    sequence:
      'ATAGCTTCAAAATGTTTCTACTCCTTTTTTACTCTTCCAGATTTTCTCGGACTCCGCGCATCGCCGTACCACTTCAAAACACCCAAGCACAGCATACTAAATTTCCCCTCTTTCTTCCTCTAGGGTGTCGTTAATTACCCGTACTAAAGGTTTGGAAAAGAAAAAAGAGACCGCCTCGTTTCTTTTTCTTCGTCGAAAAAGGCAATAAAAATTTTTATCACGTTTCTTTTTCTTGAAATTTTTTTTTTTAGTTTTTTTCTCTTTCAGTGACCTCCATTGATATTTAAGTTAATAAACGGTCTTCAATTTCTCAAGTTTCAGTTTCATTTTTCTTGTTCTATTACAACTTTTTTTACTTCTTGTTCATTAGAAAGAAAGCATAGCAATCTAATCTAAGTTTTAATTACAAA',
  },

  // ---- RBS ----
  {
    id: 'r_B0034',
    type: 'rbs',
    name: 'B0034 (medium)',
    summary: 'Standard medium-strength RBS from the iGEM Registry.',
    sequence: 'AAAGAGGAGAAA',
  },
  {
    id: 'r_strong',
    type: 'rbs',
    name: 'Strong RBS',
    summary: 'A canonical strong Shine-Dalgarno sequence with optimal spacing.',
    sequence: 'AAAGAGGAGAAATACTAG',
  },

  // ---- CDS ----
  {
    id: 'c_gfp',
    type: 'cds',
    name: 'sfGFP',
    summary: 'Superfolder green fluorescent protein. Makes cells glow green under blue light.',
    sequence:
      'ATGAGCAAAGGAGAAGAACTTTTCACTGGAGTTGTCCCAATTCTTGTTGAATTAGATGGTGATGTTAATGGGCACAAATTTTCTGTCAGAGGAGAGGGTGAAGGTGATGCTACATACGGAAAGCTTACCCTTAAATTTATTTGCACTACTGGAAAACTACCTGTTCCATGGCCAACACTTGTCACTACTCTGACCTATGGTGTTCAATGCTTTTCCCGTTATCCGGATCACATGAAACGGCATGACTTTTTCAAGAGTGCCATGCCCGAAGGTTATGTACAGGAACGCACTATATCTTTCAAAGATGACGGGACCTACAAGACGCGTGCTGAAGTCAAGTTTGAAGGTGATACCCTTGTTAATCGTATCGAGTTAAAGGGTATTGATTTTAAAGAAGATGGAAACATTCTCGGACACAAACTCGAGTACAACTTTAACTCACACAATGTATACATCACGGCAGACAAACAAAAGAATGGAATCAAAGCTAACTTCAAAATTCGCCACAACATTGAAGATGGTTCCGTTCAACTAGCAGACCATTATCAACAAAATACTCCAATTGGCGATGGCCCTGTCCTTTTACCAGACAACCATTACCTGTCGACACAATCTGCCCTTTCGAAAGATCCCAACGAAAAGCGTGACCACATGGTCCTTCTTGAGTTTGTAACTGCTGCTGGGATTACACATGGCATGGATGAGCTCTACAAATAA',
  },
  {
    id: 'c_rfp',
    type: 'cds',
    name: 'mRFP1',
    summary: 'Monomeric red fluorescent protein — makes cells red/pink.',
    sequence:
      'ATGGCTTCATCCGAGGACGTCATCAAGGAGTTCATGCGTTTCAAAGTTCGTATGGAAGGTTCCGTTAACGGTCACGAGTTCGAAATCGAAGGTGAAGGTGAAGGTCGTCCGTACGAAGGTACCCAGACCGCTAAACTGAAAGTTACCAAAGGTGGTCCGCTGCCGTTCGCTTGGGACATCCTGTCCCCGCAGTTCCAGTACGGTTCCAAAGCTTACGTTAAACACCCGGCTGACATCCCGGACTACCTGAAACTGTCCTTCCCGGAAGGTTTCAAATGGGAACGTGTTATGAACTTCGAAGACGGTGGTGTTGTTACCGTTACCCAGGACTCCTCCCTGCAAGACGGTGAGTTCATCTACAAAGTTAAACTGCGTGGTACCAACTTCCCGTCCGACGGTCCGGTTATGCAGAAAAAAACCATGGGTTGGGAAGCTTCCACCGAACGTATGTACCCGGAAGACGGTGCTCTGAAAGGTGAAATCAAAATGCGTCTGAAACTGAAAGACGGTGGTCACTACGACGCTGAAGTTAAAACCACCTACATGGCTAAAAAACCGGTTCAGCTGCCGGGTGCTTACAAAACCGACATCAAACTGGACATCACCTCCCACAACGAAGACTACACCATCGTTGAACAGTACGAACGTGCTGAAGGTCGTCACTCCACCGGTGCTTAA',
  },
  {
    id: 'c_laci',
    type: 'cds',
    name: 'lacI',
    summary: 'Lac repressor — used to build IPTG-inducible circuits.',
    sequence:
      'ATGAAACCAGTAACGTTATACGATGTCGCAGAGTATGCCGGTGTCTCTTATCAGACCGTTTCCCGCGTGGTGAACCAGGCCAGCCACGTTTCTGCGAAAACGCGGGAAAAAGTGGAAGCGGCGATGGCGGAGCTGAATTACATTCCCAACCGCGTGGCACAACAACTGGCGGGCAAACAGTCGTTGCTGATTGGCGTTGCCACCTCCAGTCTGGCCCTGCACGCGCCGTCGCAAATTGTCGCGGCGATTAAATCTCGCGCCGATCAACTGGGTGCCAGCGTGGTGGTGTCGATGGTAGAACGAAGCGGCGTCGAAGCCTGTAAAGCGGCGGTGCACAATCTTCTCGCGCAACGCGTCAGTGGGCTGATCATTAACTATCCGCTGGATGACCAGGATGCCATTGCTGTGGAAGCTGCCTGCACTAATGTTCCGGCGTTATTTCTTGATGTCTCTGACCAGACACCCATCAACAGTATTATTTTCTCCCATGAAGACGGTACGCGACTGGGCGTGGAGCATCTGGTCGCATTGGGTCACCAGCAAATCGCGCTGTTAGCGGGCCCATTAAGTTCTGTCTCGGCGCGTCTGCGTCTGGCTGGCTGGCATAAATATCTCACTCGCAATCAAATTCAGCCGATAGCGGAACGGGAAGGCGACTGGAGTGCCATGTCCGGTTTTCAACAAACCATGCAAATGCTGAATGAGGGCATCGTTCCCACTGCGATGCTGGTTGCCAACGATCAGATGGCGCTGGGCGCAATGCGCGCCATTACCGAGTCCGGGCTGCGCGTTGGTGCGGATATCTCGGTAGTGGGATACGACGATACCGAAGACAGCTCATGTTATATCCCGCCGTTAACCACCATCAAACAGGATTTTCGCCTGCTGGGGCAAACCAGCGTGGACCGCTTGCTGCAACTCTCTCAGGGCCAGGCGGTGAAGGGCAATCAGCTGTTGCCCGTCTCACTGGTGAAAAGAAAAACCACCCTGGCGCCCAATACGCAAACCGCCTCTCCCCGCGCGTTGGCCGATTCATTAATGCAGCTGGCACGACAGGTTTCCCGACTGGAAAGCGGGCAGTGA',
  },

  // ---- Terminators ----
  {
    id: 't_B0015',
    type: 'terminator',
    name: 'B0015 (rrnB T1+T7Te)',
    summary: 'Standard double terminator from the iGEM Registry. Use this one if unsure.',
    sequence: 'CCAGGCATCAAATAAAACGAAAGGCTCAGTCGAAAGACTGGGCCTTTCGTTTTATCTGTTGTTTGTCGGTGAACGCTCTCTACTAGAGTCACACTGGCTCACCTTCGGGTGGGCCTTTCTGCGTTTATA',
  },
  {
    id: 't_T7',
    type: 'terminator',
    name: 'T7 terminator',
    summary: 'Short terminator paired with the T7 promoter.',
    sequence: 'CTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTG',
  },
  {
    id: 't_ADH1',
    type: 'terminator',
    name: 'ADH1 terminator (yeast)',
    summary: 'Common terminator for yeast expression cassettes.',
    sequence: 'GCGAATTTCTTATGATTTATGATTTTTATTATTAAATAAGTTATAAAAAAAATAAGTGTATACAAATTTTAAAGTGACTCTTAGGTTTTAAAACGAAAATTCTTATTCTTGAGTAACTCTTTCCTGTAGGTCAGGTTGCTTTCTCAGGTATAGTATGAGGTCGCTCTTATTGACCACACCTCTACCGGCATGCCGAGCAAATGCCTGCAAATCGCTCCCCATTTCACCCAATTGTAGATATGCTAACTCCAGCAATGAGTTGATGAATCTCGGTGTGTATTTTATGTCCTCAGAGGACAACACCT',
  },

  // ---- Origins ----
  {
    id: 'o_pUC',
    type: 'origin',
    name: 'pUC origin',
    summary: 'High-copy E. coli origin (~500 copies per cell). Most pUC/pBlueScript backbones use this.',
    sequence:
      'TTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTCCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAA',
  },
  {
    id: 'o_p15a',
    type: 'origin',
    name: 'p15A origin',
    summary: 'Medium-copy E. coli origin (~10–12 copies per cell). Compatible with pUC plasmids.',
    sequence:
      'AAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAG',
  },
  {
    id: 'o_2micron',
    type: 'origin',
    name: '2µ origin (yeast)',
    summary: 'High-copy yeast origin from the native 2-micron plasmid.',
    sequence: 'AAGCATGTAATAATTAACATGTAATGCATGACGTTATTTATGAGATGGGTTTTTATGATTAGAGTCCCGCAATTATACATTTAATACGCGATAGAAAACAAAATATAGCGCGCAAACTAGGATAAATTATCGCGCGCGGTGTCATCTATGTTACTAGATC',
  },

  // ---- Resistance markers ----
  {
    id: 'm_ampR',
    type: 'resistance',
    name: 'AmpR (bla)',
    summary: 'Ampicillin / β-lactamase resistance. Most common selection marker in E. coli cloning.',
    sequence:
      'ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTATTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAA',
  },
  {
    id: 'm_kanR',
    type: 'resistance',
    name: 'KanR (neo)',
    summary: 'Kanamycin resistance (neomycin phosphotransferase II). Common in pET vectors.',
    sequence:
      'ATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCGACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAAGAGCATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGCGCATGCCCGACGGCGAGGATCTCGTCGTGACCCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTGTGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAGCTTGGCGGCGAATGGGCTGACCGCTTCCTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTGA',
  },
];

/* Worked example: a simple GFP expression cassette + selection + origin */
const EXAMPLE_ASSEMBLY = [
  'p_J23100', 'r_B0034', 'c_gfp', 't_B0015', 'o_pUC', 'm_ampR',
];

window.PART_TYPE_META = PART_TYPE_META;
window.PART_LIBRARY = PART_LIBRARY;
window.EXAMPLE_ASSEMBLY = EXAMPLE_ASSEMBLY;
